name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install packages
      run: sudo apt update; sudo apt install nasm qemu-system-x86
    - name: assemble
      run: make
    - name: take a dookie of the BIOS binary
      run: ndisasm -b 16 bios.bin
    - name: test
      run: timeout -s 2 --preserve-status 30s qemu-system-i386 -bios bios.bin -serial stdio -display none
