name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install packages
      run: sudo apt install nasm 
    - name: assemble
      run: make
    - name: take a dookie of the BIOS binary
      run: |
        echo "::group::view the dookie of the BIOS"
        ndisasm -b 16 bios.bin
        echo "::endgroup::"
    - name: test
      run: timeout -s 2 --preserve-status 5s qemu-system-i386 -bios bios.bin -serial stdio -display none
